services:
  - type: web
    name: TEST
    runtime: node
    repo: https://github.com/respowerr/cloud4
    region: frankfurt
    plan: free
    branch: main
    buildCommand: npm install
    startCommand: npm run start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: GROSSE_DB
          property: connectionString
databases:
  - name: GROSSE_DB
    region: frankfurt
    plan: free